### ISSUE TITLE
Location motion sensors no longer working

### ISSUE THREAD

**Issue by r2shyyou** [adhyh/homebridge-vwconnectid#6]
**Describe The Bug:**
My "Home" location motion sensor stopped working after updating to 1.0.4. I've since updated to 1.0.5 but it's still not working.

**Environment:**

* **Plugin Version**: 1.0.5
* **Homebridge Version**: 1.6.0
* **Node.js Version**: 18.15.0
* **NPM Version**: 9.5.0
* **Operating System**: Raspbian

**Comment by adhyh** [comment]
Hmm, that's interesting. I just checked and Location sensors are still working on my setup with 1.0.5.

Just to confirm, you did move the car -for a few minutes at least- after restarting homebridge right?

With "logLevel": "DEBUG" in your config, do you see lines like this in your log showing up:
``DEBUG: getIdParkingPosition: {"data":{"lon":5.xxxxx,"lat":52.xxxxx,"carCapturedTimestamp":"2023-03-25T13:16:43Z"}}``

When you create a **new** location sensor with -say- the coordinates of a nearby supermarket, and a fairly large radius, does that one work?

You could try resettnig the accessory by removing the motion sensor from the cache (homebridge settings -> remove a single accessory from cache; check for duplicates of the motion sensor and remove all, then restart HB. The accessory will be added as new).

**Comment by r2shyyou** [comment]
> Just to confirm, you did move the car -for a few minutes at least- after restarting homebridge right?

yes, i did 

> With "logLevel": "DEBUG" in your config, do you see lines like this in your log showing up:
DEBUG: getIdParkingPosition: {"data":{"lon":5.xxxxx,"lat":52.xxxxx,"carCapturedTimestamp":"2023-03-25T13:16:43Z"}}

yes, i do

> When you create a temprary event motion sensor that listens to 'parked' event, does that one trigger when parking the car?

the event motion sensor for parking works great, it's the location motion sensor that isn't working

> You could try resetting the accessory by removing the motion sensor from the cache (homebridge settings -> remove a single accessory from cache; check for duplicates of the motion sensor and remove all, then restart HB. The accessory will be added as new).

i tried this, and it didn't seem to change anything

**Comment by adhyh** [comment]
The location motion sensor uses the parking event with gps data to trigger the location motion sensor. 

I think in some cases the parking event is triggered before the GPS data is received from the backend. In those cases the location sensor would fail. I will take a look.

**Comment by r2shyyou** [comment]
thanks. currently i'm getting this:

`DEBUG: getIdParkingPosition: undefined`

and this:

`ERROR: get id parking position Failed`

so the issue may be on my side, or with WeConnectID. maybe has to do with parking in an underground garage? i don't know. it used to work great. i'll try to play around with the radius...

**Comment by r2shyyou** [comment]
this probably doesn't help...
![image](https://user-images.githubusercontent.com/3274534/227776428-f4679ce2-cb7a-4790-9806-47359fd00b71.jpeg)

**Comment by r2shyyou** [comment]
i created a location motion sensor for a location other than my home (underground garage) and it works! so, seems the issue is my home :( oh well.

**Comment by adhyh** [comment]
Looks like indeed the GPS signal is weak in your garage. But, at some point at least the car is able to fetch a signal. 

I made a small update to the communication module that waits for a gps coordinate and then fires the parking / locations sensors events. Before I roll it out, could you try if it solves anything?

with "logLevel": "INFO" (to filter useful information), could you run the following line (it's one line) in Hombridge Terminal (hidden under the + sign):

``mv $UIX_CUSTOM_PLUGIN_PATH/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js $UIX_CUSTOM_PLUGIN_PATH/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/index.js.orig && wget https://raw.githubusercontent.com/adhyh/npm-vwconnectidapi/fix-location-sensors/index.js -P $UIX_CUSTOM_PLUGIN_PATH/homebridge-vwconnectid/node_modules/npm-vwconnectidapi/``

then restart HB and go for a ride. You should see ``ERROR: TypeError: Cannot read properties of undefined (reading 'data')
ERROR: get id parking position Failed`` at least once, it means the plugin knows you're on the move.

then post back what the plugin reports about your parking action. I made this more verbose in order to debug what's going on.

**Comment by r2shyyou** [comment]
thanks! the location sensor wasn't triggered but i updated the coordinates to match what the log reported:

> ERROR: TypeError: Cannot read properties of undefined (reading 'data')
> ERROR: get id parking position Failed
> INFO:  Car is parked at: {"data":{"lon":X.XXXXXX,"lat":X.XXXXXX,"carCapturedTimestamp":"2023-03-28T09:34:00Z","carIsParked":true}}

**Comment by adhyh** [comment]
Good. This looks like an issue that can be solved. 

Possibly, because of a weak signal in your garage, you have a low gps accuracy. So you may also play around with the radius setting. You can check the reported location in google maps and see if it is off by a lot.

**Comment by r2shyyou** [comment]
question: if i set the location motion sensor coordinates to the same as those in the "car is parked" info message, why wouldn't the location motion sensor go off?
